### ISSUE TITLE
[Suggestion] New Logo for WhatTodo

### ISSUE THREAD

**Issue by zularizal** [burhanrashid52/WhatTodo#1]
Hello @burhanrashid52 , I want to contribute to your project, I want to create a new logo and icon for this application with material design style and it's free. Do you want it?

**Comment by burhanrashid52** [comment]
Yeah sure

**Comment by zularizal** [comment]
Hi, I have designed it, what do you think, If there is something you want to change, please let me know.

And I'm having a little trouble putting a check mark, what do you think the number you like?

![logo](https://user-images.githubusercontent.com/38547278/39993685-e42137fe-57a0-11e8-8279-405300637b40.png)

**Comment by burhanrashid52** [comment]
I like the first one. But it would be better if we that red check mark at the beginning of every line i.e green, blue, yellow and purple and remove the check mark from the centre. your suggestion? @zularizal

**Comment by zularizal** [comment]
I agree, this looks good and cool. But which one do you like? 1, 2 or 3

![2](https://user-images.githubusercontent.com/38547278/40007458-08f5882a-57c7-11e8-8ca9-5413b03bf33f.png)

**Comment by burhanrashid52** [comment]
I like first one. Generate PR for this

**Comment by zularizal** [comment]
Okay @burhanrashid52  , I've uploaded the logo files to drive. 

https://drive.google.com/open?id=1YnXqS9ArDu2NvuARPVTQpNhqtzwAJGTy

And I've sent Pull Request, please check #2
