### ISSUE TITLE
 Please i need to ake a database with a many tables with sqflite can you help me please

### ISSUE THREAD

**Issue by amina04** [burhanrashid52/WhatTodo#18]

**Comment by burhanrashid52** [comment]
Sorry. I did not understand. Can you please elaborate with an example?

**Comment by amina04** [comment]
> Sorry. I did not understand. Can you please elaborate with an example?

[i have a class diagramme and i want to transform it on a database this diagramme has more then one table , and i didn't found any tutorial for make that on youtube .please could you help me this is my end of studies' project. when i saw your project i found that you made a database with many tables but i didn't understand . please help me this is my diagram 
![ClassDiagram1](https://user-images.githubusercontent.com/63787547/87873310-d274df80-c9c0-11ea-9bbf-4e82be0f7533.jpg)
i can't send to you an image here i will send it to you in gmail please chack it i beg you

**Comment by nightscape** [comment]
I think this can be closed...

**Comment by amina04** [comment]
thank you. i slove it in august
