### ISSUE TITLE
line 95 of home.dart - Failed assertion: boolean expression must not be null - isDataChanged

### ISSUE THREAD

**Issue by marcelmenezes** [burhanrashid52/WhatTodo#4]
Debugging on iPhone 5s, when I click to add a task, it opens the Add Task route.  And when then I press the upper "back" button, on home.dart line 95 (if (isDataChanged) {) It shows "Failed assertion: boolean expression must not be null"

It seems that you are not using the right way to get the value of "isDataChanged".

**Comment by burhanrashid52** [comment]
The issue is fixed in v.0.2.0. WhatTodo is migrated to BLoC pattern.
